<template>
    <div class="py-24 max-w-[1440px] margine">
        <p class="text-black text-center text-p3 font-title">Current as of 20 Jan 2022</p>
        <h1 class="text-grey-900 text-center text-h3 font-paragraph mt-3 md:text-h1">FAQ - Domande frequenti</h1>
        <p class="text-grey-500 text-center text-p2 font-paragraph mt-6">Your privacy is important to us at Untitled. We respect your privacy regarding any information we may collect from you across our website.</p>
        <div class="mt-[100px] mx-5">
            <p class="text-grey-500 text-[18px] font-paragraph leading-7">Mi tincidunt elit, id quisque ligula ac diam, amet. Vel etiam suspendisse morbi eleifend faucibus eget vestibulum felis. Dictum quis montes, sit sit. Tellus aliquam enim urna, etiam. Mauris posuere vulputate arcu amet, vitae nisi, tellus tincidunt. At feugiat sapien varius id. Eget quis mi enim, leo lacinia pharetra, semper. Eget in volutpat mollis at volutpat lectus velit, sed auctor. Porttitor fames arcu quis fusce augue enim. Quis at habitant diam at. Suscipit tristique risus, at donec. In turpis vel et quam imperdiet. Ipsum molestie aliquet sodales id est ac volutpat.</p>
            <h4 class="text-grey-900 text-p1 mt-[50px] font-medium md:text-h4">What information do we collect?</h4>
            <p class="text-grey-500 text-[18px] mt-6 font-paragraph leading-7">Dolor enim eu tortor urna sed duis nulla. Aliquam vestibulum, nulla odio nisl vitae. In aliquet pellentesque aenean hac vestibulum turpis mi bibendum diam. Tempor integer aliquam in vitae malesuada fringilla. Elit nisi in eleifend sed nisi. Pulvinar at orci, proin imperdiet commodo consectetur convallis risus. Sed condimentum enim dignissim adipiscing faucibus consequat, urna. Viverra purus et erat auctor aliquam. Risus, volutpat vulputate posuere purus sit congue convallis aliquet. Arcu id augue ut feugiat donec porttitor neque. Mauris, neque ultricies eu vestibulum, bibendum quam lorem id. Dolor lacus, eget nunc lectus in tellus, pharetra, porttitor. Ipsum sit mattis nulla quam nulla. Gravida id gravida ac enim mauris id. Non pellentesque congue eget consectetur turpis. Sapien, dictum molestie sem tempor. Diam elit, orci, tincidunt aenean tempus. Quis velit eget ut tortor tellus. Sed vel, congue felis elit erat nam nibh orci.</p>
            <h4 class="text-grey-900 text-p1 mt-[50px] font-medium md:text-h4">How do we use your information?</h4>
            <p class="text-grey-500 text-[18px] mt-6 font-paragraph leading-7">Dolor enim eu tortor urna sed duis nulla. Aliquam vestibulum, nulla odio nisl vitae. In aliquet pellentesque aenean hac vestibulum turpis mi bibendum diam. Tempor integer aliquam in vitae malesuada fringilla. Elit nisi in eleifend sed nisi. Pulvinar at orci, proin imperdiet commodo consectetur convallis risus. Sed condimentum enim dignissim adipiscing faucibus consequat, urna. Viverra purus et erat auctor aliquam. Risus, volutpat vulputate posuere purus sit congue convallis aliquet. Arcu id augue ut feugiat donec porttitor neque. Mauris, neque ultricies eu vestibulum, bibendum quam lorem id. Dolor lacus, eget nunc lectus in tellus, pharetra, porttitor. Ipsum sit mattis nulla quam nulla. Gravida id gravida ac enim mauris id. Non pellentesque congue eget consectetur turpis. Sapien, dictum molestie sem tempor. Diam elit, orci, tincidunt aenean tempus. Quis velit eget ut tortor tellus. Sed vel, congue felis elit erat nam nibh orci.</p>
            <h5 class="text-grey-900 text-p2 mt-[50px] font-medium md:text-p1">Do we use cookies and other tracking technologies?</h5>
            <p class="text-grey-500 text-[18px] mt-6 font-paragraph leading-7">Pharetra morbi libero id aliquam elit massa integer tellus. Quis felis aliquam ullamcorper porttitor. Pulvinar ullamcorper sit dictumst ut eget a, elementum eu. Maecenas est morbi mattis id in ac pellentesque ac.</p>
            <h5 class="text-grey-900 text-p2 mt-[50px] font-medium md:text-p1">How long do we keep your information?</h5>
            <p class="text-grey-500 text-[18px] mt-6 font-paragraph leading-7">Pharetra morbi libero id aliquam elit massa integer tellus. Quis felis aliquam ullamcorper porttitor. Pulvinar ullamcorper sit dictumst ut eget a, elementum eu. Maecenas est morbi mattis id in ac pellentesque ac.</p>
            <h5 class="text-grey-900 text-p2 mt-[50px] font-medium md:text-p1">How long do we keep your information safe?</h5>
            <p class="text-grey-500 text-[18px] mt-6 font-paragraph leading-7">Pharetra morbi libero id aliquam elit massa integer tellus. Quis felis aliquam ullamcorper porttitor. Pulvinar ullamcorper sit dictumst ut eget a, elementum eu. Maecenas est morbi mattis id in ac pellentesque ac.</p>
            <h4 class="text-grey-900 text-p1 mt-[50px] font-medium md:text-h4">What are your privacy rights?</h4>
            <p class="text-grey-500 text-[18px] mt-6 font-paragraph leading-7">Dolor enim eu tortor urna sed duis nulla. Aliquam vestibulum, nulla odio nisl vitae. In aliquet pellentesque aenean hac vestibulum turpis mi bibendum diam. Tempor integer aliquam in vitae malesuada fringilla. Elit nisi in eleifend sed nisi. Pulvinar at orci, proin imperdiet commodo consectetur convallis risus. Sed condimentum enim dignissim adipiscing faucibus consequat, urna. Viverra purus et erat auctor aliquam. Risus, volutpat vulputate posuere purus sit congue convallis aliquet. Arcu id augue ut feugiat donec porttitor neque. Mauris, neque ultricies eu vestibulum, bibendum quam lorem id. Dolor lacus, eget nunc lectus in tellus, pharetra, porttitor. Ipsum sit mattis nulla quam nulla. Gravida id gravida ac enim mauris id. Non pellentesque congue eget consectetur turpis. Sapien, dictum molestie sem tempor. Diam elit, orci, tincidunt aenean tempus. Quis velit eget ut tortor tellus. Sed vel, congue felis elit erat nam nibh orci.</p>
            <h5 class="text-grey-900 text-p2 mt-[50px] font-medium md:text-p1">How can you contact us about this policy?</h5>
            <p class="text-grey-500 text-[18px] mt-6 font-paragraph leading-7">Sagittis et eu at elementum, quis in. Proin praesent volutpat egestas sociis sit lorem nunc nunc sit. Eget diam curabitur mi ac. Auctor rutrum lacus malesuada massa ornare et. Vulputate consectetur ac ultrices at diam dui eget fringilla tincidunt. Arcu sit dignissim massa erat cursus vulputate gravida id. Sed quis auctor vulputate hac elementum gravida cursus dis.
Lectus id duis vitae porttitor enim gravida morbi.
Eu turpis posuere semper feugiat volutpat elit, ultrices suspendisse. Auctor vel in vitae placerat.
Suspendisse maecenas ac donec scelerisque diam sed est duis purus.</p>
        </div>
    </div>
</template>

<style>
@media screen and (min-width: 768px) {
    .margine {
        margin: 0 auto;
    }
}
</style>